// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: hackcart43

#ifndef _HACKCART43_UI_H
#define _HACKCART43_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
void SlideKeyboardUp_Animation( lv_obj_t *TargetObject, int delay);
void HideKeyboard_Animation( lv_obj_t *TargetObject, int delay);
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Header;
extern lv_obj_t *ui_SatInfoPanel;
extern lv_obj_t *ui_LabelSatCount;
extern lv_obj_t *ui_SatIcon;
extern lv_obj_t *ui_TimePanel;
extern lv_obj_t *ui_LabelTime;
void ui_event_Panel5( lv_event_t * e);
extern lv_obj_t *ui_Panel5;
extern lv_obj_t *ui_ArcSpeed;
extern lv_obj_t *ui_LabelSpeed;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
void ui_event_Screen2( lv_event_t * e);
extern lv_obj_t *ui_Screen2;
extern lv_obj_t *ui_WifiFormPanel;
extern lv_obj_t *ui_LabelWifiSettings;
extern lv_obj_t *ui_PanelWIfiSettings;
extern lv_obj_t *ui_DropdownSSID;
void ui_event_TextAreaWifiPassword( lv_event_t * e);
extern lv_obj_t *ui_TextAreaWifiPassword;
extern lv_obj_t *ui_PanelWIfiSettingsButtons;
void ui_event_ButtonCancelWifi( lv_event_t * e);
extern lv_obj_t *ui_ButtonCancelWifi;
extern lv_obj_t *ui_LabelCancelWifi;
void ui_event_ButtonSaveWifi( lv_event_t * e);
extern lv_obj_t *ui_ButtonSaveWifi;
extern lv_obj_t *ui_LabelSaveWifi;
void ui_event_Keyboard1( lv_event_t * e);
extern lv_obj_t *ui_Keyboard1;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_satellite_icon_png);   // assets/satellite_icon.png



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
