// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: hackcart43

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_img_src( ui_Screen1, &ui_img_mock_png, LV_PART_MAIN | LV_STATE_DEFAULT );

ui_LabelSpeed = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_LabelSpeed, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelSpeed, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelSpeed, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelSpeed,"25");
lv_obj_set_style_text_color(ui_LabelSpeed, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelSpeed, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelSpeed, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ArcSpeed = lv_arc_create(ui_Screen1);
lv_obj_set_width( ui_ArcSpeed, 150);
lv_obj_set_height( ui_ArcSpeed, 150);
lv_obj_set_align( ui_ArcSpeed, LV_ALIGN_CENTER );
lv_arc_set_range(ui_ArcSpeed, 0,45);
lv_arc_set_value(ui_ArcSpeed, 30);
lv_obj_set_style_arc_color(ui_ArcSpeed, lv_color_hex(0x1EC333), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_ArcSpeed, 50, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_ArcSpeed, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_ArcSpeed, lv_color_hex(0x1AC141), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_ArcSpeed, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_ArcSpeed, 5, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_ArcSpeed, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ArcSpeed, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

}
