// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: hackcart43

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Header = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_Header, 480);
lv_obj_set_height( ui_Header, 50);
lv_obj_set_align( ui_Header, LV_ALIGN_TOP_MID );
lv_obj_set_flex_flow(ui_Header,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Header, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Header, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Header, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Header, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Header, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Header, lv_color_hex(0x242424), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Header, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_Header, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_Header, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Header, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SatInfoPanel = lv_obj_create(ui_Header);
lv_obj_set_width( ui_SatInfoPanel, 64);
lv_obj_set_height( ui_SatInfoPanel, 32);
lv_obj_set_x( ui_SatInfoPanel, -199 );
lv_obj_set_y( ui_SatInfoPanel, -2 );
lv_obj_set_align( ui_SatInfoPanel, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_SatInfoPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_SatInfoPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SatInfoPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelSatCount = lv_label_create(ui_SatInfoPanel);
lv_obj_set_width( ui_LabelSatCount, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelSatCount, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelSatCount, 14 );
lv_obj_set_y( ui_LabelSatCount, 0 );
lv_obj_set_align( ui_LabelSatCount, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelSatCount,"0");
lv_obj_set_style_text_color(ui_LabelSatCount, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelSatCount, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SatIcon = lv_img_create(ui_SatInfoPanel);
lv_img_set_src(ui_SatIcon, &ui_img_satellite_icon_png);
lv_obj_set_width( ui_SatIcon, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SatIcon, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SatIcon, -10 );
lv_obj_set_y( ui_SatIcon, -1 );
lv_obj_set_align( ui_SatIcon, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_SatIcon, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_SatIcon, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_TimePanel = lv_obj_create(ui_Header);
lv_obj_set_width( ui_TimePanel, 92);
lv_obj_set_height( ui_TimePanel, 32);
lv_obj_set_x( ui_TimePanel, 252 );
lv_obj_set_y( ui_TimePanel, -53 );
lv_obj_set_align( ui_TimePanel, LV_ALIGN_TOP_MID );
lv_obj_set_flex_flow(ui_TimePanel,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_TimePanel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_TimePanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_TimePanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TimePanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelTime = lv_label_create(ui_TimePanel);
lv_obj_set_width( ui_LabelTime, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelTime, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelTime, 3 );
lv_obj_set_y( ui_LabelTime, -1 );
lv_obj_set_align( ui_LabelTime, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelTime,"10:24 am");
lv_obj_set_style_text_color(ui_LabelTime, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelTime, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel5 = lv_obj_create(ui_Header);
lv_obj_set_width( ui_Panel5, 38);
lv_obj_set_height( ui_Panel5, 32);
lv_obj_set_x( ui_Panel5, 45 );
lv_obj_set_y( ui_Panel5, -118 );
lv_obj_set_align( ui_Panel5, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ArcSpeed = lv_arc_create(ui_Screen1);
lv_obj_set_width( ui_ArcSpeed, 150);
lv_obj_set_height( ui_ArcSpeed, 150);
lv_obj_set_x( ui_ArcSpeed, 7 );
lv_obj_set_y( ui_ArcSpeed, 25 );
lv_obj_set_align( ui_ArcSpeed, LV_ALIGN_CENTER );
lv_arc_set_range(ui_ArcSpeed, 0,45);
lv_arc_set_value(ui_ArcSpeed, 20);
lv_obj_set_style_arc_color(ui_ArcSpeed, lv_color_hex(0x1EC333), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_ArcSpeed, 50, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_ArcSpeed, 15, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_ArcSpeed, false, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_outline_color(ui_ArcSpeed, lv_color_hex(0xF70000), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_ArcSpeed, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(ui_ArcSpeed, 2, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_ArcSpeed, 2, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_color(ui_ArcSpeed, lv_color_hex(0x1AC141), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_ArcSpeed, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_ArcSpeed, 15, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_ArcSpeed, false, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_ArcSpeed, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ArcSpeed, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_LabelSpeed = lv_label_create(ui_ArcSpeed);
lv_obj_set_width( ui_LabelSpeed, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelSpeed, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelSpeed, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelSpeed,"0");
lv_obj_set_style_text_color(ui_LabelSpeed, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelSpeed, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelSpeed, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

}
